import { EquipmentCategory, FiaTechnicalList } from "../types";
import list74 from "./list-74.json";
import list57 from "./list-57.json";
import list24 from "./list-24.json";
import list16 from "./list-16.json";
import list12 from "./list-12.json";
import list27 from "./list-27.json";
import list29 from "./list-29.json";
import list40 from "./list-40.json";
import list91 from "./list-91.json";

/**
 * Parsed FIA Technical Lists — see fia-lists/README.md for how these are generated
 * (scripts/parse-fia-list.mjs against a cached PDF). Only the lists whose table format has
 * actually been verified against real entries are wired in here; see that script's
 * LIST_CONFIG for the ones still pending.
 *
 * List 24 in particular: its table has extra columns (strap/attachment counts and buckle type)
 * this app doesn't use, which the current parser doesn't cleanly separate from manufacturer/
 * model — so those two display fields are unreliable specifically for this list. The
 * safety-relevant fields (homologation number, dates, revoked) are unaffected.
 *
 * List 12 (FIA 8855-1999 seats) is hand-transcribed, like List 91 below — its table drifts the
 * MODEL and DATE columns out of sync with the NUMBER/BRAND columns as pdftotext -layout reads
 * down each page (not a clean, reversible offset; it varies row to row and resets each page
 * break), so the generic parser silently attributed one product's model/dates to a different,
 * nearby number throughout the whole list, not just a messy section. All 599 entries are
 * hand-verified against the rendered pages — see LIST_12_MANUAL_ENTRIES in the parser script.
 *
 * List 16 (FIA 8865-2015 fire extinguisher systems) is hand-transcribed too, for a different
 * reason: many rows have a multi-line MODEL cell (several alternate part numbers stacked
 * together, e.g. one homologation covering six FX G-TEC variants), and the generic parser
 * dropped most of these rows outright rather than misattributing them — it found only 14 of the
 * real 74 entries. All 74 are hand-verified — see LIST_16_MANUAL_ENTRIES. This list has no
 * separate "valid until" column, so `validUntil` is never set for it.
 *
 * List 27 (FIA 8856-2000) is scoped to `categories: ["firesuit"]` — only its Part 1 (numbered
 * overalls/suits) is wired up. Its Part 2 (undergarment/balaclava/sock/shoe manufacturers) and
 * Part 3 (gloves) are "approved manufacturer/model" lists with no homologation number at all,
 * so there's nothing for this app's number-lookup UI to check for those categories under this
 * older standard — see FiaTechnicalList.categories' doc comment.
 *
 * List 29 (FIA 8858-2010) is scoped to `categories: ["hnr"]` — only its Part 1 (numbered FHR
 * devices) is wired up. Its Part 2 (tether systems) and the appended older FIA 8858-2002 section
 * are both non-numbered "approved manufacturer/model" lists, same situation as List 27's Parts
 * 2/3. No revocations found in this list.
 *
 * List 40 (FIA 8862-2009 advanced racing seats) is hand-transcribed, like Lists 12 and 91 — a
 * model name (e.g. AS.002.10's RT4129WTHR) can land on a text line disconnected from its own
 * number and brand entirely, while OTHER numbers on the same page keep model correctly on their
 * own line, with no reliable way to tell which case a given number falls into from the text
 * alone. All 113 entries are hand-verified against the rendered pages — see
 * LIST_40_MANUAL_ENTRIES in the parser script. Brackets were unregulated under this standard
 * (unlike List 91's 8855-2021), so this list carries no approvedBrackets data.
 *
 * List 91 (FIA 8855-2021 competition seats) is hand-transcribed from the rendered PDF pages, not
 * generated by scripts/parse-fia-list.mjs's generic text-based row parser — the parser was tried
 * first, but cross-checking its output against the actual pages (via `pdftoppm`) showed
 * `pdftotext -layout` doesn't reliably keep a homologation number in the same reading-order
 * position as the product row it belongs to (e.g. CS.002.21/CS.003.21 looked like bracket
 * variants of CS.001.21 in the text, but are actually two entirely different seat models). All 33
 * entries are complete and verified against the source images — see fia-lists/README.md and
 * LIST_91_MANUAL_ENTRIES in the parser script. Each entry's `approvedBrackets` lists every
 * bracket FIA homologated together with that specific seat — this is the first seat standard to
 * require that pairing (brackets were unregulated under 8855-1999/List 12 and 8862-2009/List 40).
 */
export const FIA_TECHNICAL_LISTS: FiaTechnicalList[] = [
  list74,
  list57,
  list24,
  list16,
  list12,
  list27,
  list29,
  list40,
  list91,
] as FiaTechnicalList[];

/**
 * This app's standardId -> the FIA Technical List(s) that are its homologation register. Pass
 * the category too when known (it always is, in practice — see CertificationRow) so a list
 * scoped to specific categories (see FiaTechnicalList.categories) doesn't show up for a category
 * it doesn't actually assign numbers to.
 */
export function fiaListsForStandard(standardId: string, category?: EquipmentCategory): FiaTechnicalList[] {
  return FIA_TECHNICAL_LISTS.filter(
    (l) => l.standardIds.includes(standardId) && (!l.categories || (category !== undefined && l.categories.includes(category)))
  );
}
